# unum todo
* finetune hnsw (find the best param setting)
* check multivector (super super useful for question id)

In [1]:
import numpy as np
from usearch.index import Index


In [ ]:

index = Index(ndim=3)               # Default settings for 3D vectors
vector = np.array([0.2, 0.6, 0.4])  # Can be a matrix for batch operations
index.add(42, vector)               # Add one or many vectors in parallel
matches = index.search(vector, 10)  # Find 10 nearest neighbors

assert matches[0].key == 42
assert matches[0].distance <= 0.001
assert np.allclose(index[42], vector, atol=0.1) # Ensure high tolerance in mixed-precision comparisons

In [ ]:
index = Index(ndim=1024, )
keys = np.arange(100000)
vectors = np.random.random((100000, 1024))
index.add(keys, vectors)

array([    0,     1,     2, ..., 99997, 99998, 99999], dtype=uint64)

In [39]:
%%time
matches = index.search(vectors=vectors[:1000], count=50)
matches

CPU times: user 1.64 s, sys: 4.96 ms, total: 1.64 s
Wall time: 182 ms


usearch.BatchMatches(50000 across 1000 queries)

In [30]:
vectors[0]

array([0.07052895, 0.89867761, 0.09753575, ..., 0.4275388 , 0.18333473,
       0.21067043])

In [31]:
vectors[50892]

array([0.71425007, 0.58777657, 0.12181378, ..., 0.90180302, 0.68933324,
       0.69769334])

In [40]:
for match in matches:
    print(match[0].key)

50892
92063
83585
3
4
76853
6
2922
74154
9
10
11
12
13
17642
15
16
17
93268
76739
20
21
22
23
24
25
75402
27
66991
29
30
70384
9638
33
33759
35
8645
68936
38
73207
40
41
42
43
44
25603
46
47
48
83678
50
51
52
53
1277
55
56
57
58
54323
87253
61
62
64555
27465
36169
66
67
68
69
70
71
72
63610
74
43616
76
77
78
79
80
69825
41249
96998
46823
85
1918
87
88
40213
90
91
32625
93
94
52258
96
25068
75471
99
100
101
30642
103
104
92079
75190
88717
32034
109
110
94678
112
77949
114
115
54598
44026
118
91679
84326
121
35011
123
124
125
4200
127
128
33726
130
131
132
133
72990
135
136
58917
138
139
140
141
2898
143
83381
145
146
1210
148
26270
150
86601
69424
153
154
155
51587
157
158
159
34986
161
61676
163
164
165
166
167
168
73290
170
171
12752
173
61311
51786
34572
177
178
179
83681
181
182
183
36543
185
186
187
188
69814
190
191
192
193
68924
51178
196
50477
25991
32052
25225
75521
25734
203
204
205
206
207
6649
7532
26735
76041
212
213
67008
215
216
217
218
219
220
221
222
223
61633
1210
1685