In [1]:
from torch.utils.data import Dataset, DataLoader

In [3]:
class MyDataset(Dataset):
    def __init__(self, nums: list[int]) -> None:
        self.nums = nums
        self.multiplier = 1
    def __len__(self) -> int:
        return len(self.nums)
    def __getitem__(self, i: int) -> int:
        return self.nums[i] * self.multiplier
    def incr_multiplier(self) -> None:
        self.multiplier += 1

In [4]:
numbers = [1,2,3,4,5,6,7,8]
ds = MyDataset(numbers)
loader = DataLoader(ds, batch_size=2)

In [62]:
for batch in loader:
    loader.dataset.incr_multiplier()
    print(batch)

tensor([197, 394])
tensor([594, 792])
tensor([ 995, 1194])
tensor([1400, 1600])
