In [2]:
import numpy as np
from usearch.index import Index
from sklearn.neighbors import NearestNeighbors

In [7]:
index = Index(ndim=1024, multi=True)
keys = np.arange(10000)
vectors = np.random.random((10000, 1024))
index.add(keys, vectors)

array([   0,    1,    2, ..., 9997, 9998, 9999], dtype=uint64)

In [12]:
%%time
matches = index.search(vectors=vectors[:7000], count=100)
matches

CPU times: user 5.45 s, sys: 33.4 ms, total: 5.49 s
Wall time: 688 ms


usearch.BatchMatches(700000 across 7000 queries)

In [ ]:
for match,i  in zip(matches, range(100)):
    print(match[0].key)

In [51]:
nn = NearestNeighbors(n_neighbors=13, algorithm="brute", metric="cosine")
nn.fit(vectors);

In [57]:
ranks = nn.kneighbors(vectors[:4], return_distance=False)
ranks

array([[   0, 2012, 7705, 1411, 8644, 6467, 6986, 7035, 7331, 2050, 6393,
        4798, 8374],
       [   1, 4320, 6571,  562, 4941,   95, 7828, 5317,  249,  590, 9239,
        3568, 4659],
       [   2, 2348, 8471, 9758, 3308, 7716, 4336, 1850, 3344, 3232,  429,
        9966, 1692],
       [   3, 5180, 7106, 6950, 3808,  507, 6559, 5742, 3992, 3811,  242,
        1022, 2058]])

In [58]:
hards = []
q_mis_ids = [0, 4320, 99, 6950]
k = 5
for i, top_n_miscons in enumerate(ranks):  
    hards.append(top_n_miscons[top_n_miscons != q_mis_ids[i]][:k].tolist())
hards

[[2012, 7705, 1411, 8644, 6467],
 [1, 6571, 562, 4941, 95],
 [2, 2348, 8471, 9758, 3308],
 [3, 5180, 7106, 3808, 507]]

In [56]:
rank[rank != 3][:5]

array([5180, 7106, 6950, 3808,  507])

In [41]:
np.all(rank[:, 0] == np.arange(7000))

True